use crate::services::tech_detector::{
    Framework, Language, TechScanResult, ToolConfig,
};
use serde::{Deserialize, Serialize};
use std::path::Path;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum InitError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Scan error: {0}")]
    Scan(#[from] crate::services::tech_detector::DetectorError),
    #[error("Path not found: {0}")]
    PathNotFound(String),
}

/// A single generated rule for AGENTS.md
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedRule {
    pub id: String,
    pub category: RuleCategory,
    pub content: String,
    pub source: RuleSource,
    pub accepted: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleCategory {
    TechStack,
    Directory,
    Linter,
    GitPattern,
    BestPractice,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSource {
    LinterConfig(String),
    TechStackDetection,
    DirectoryStructure,
    GitLogAnalysis,
    FrameworkBestPractice,
}

/// A file to be generated by the initializer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub rel_path: String,
    pub content: String,
    pub description: String,
    pub overwrite: bool,
}

/// The complete initialization plan (preview before writing)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitPlan {
    pub scan_result: TechScanResult,
    pub mode: InitMode,
    pub rules: Vec<GeneratedRule>,
    pub files: Vec<GeneratedFile>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InitMode {
    Fresh,
    Enhance,
}

/// Generate an initialization plan from scan results.
/// This is the deterministic layer — no LLM calls.
pub fn generate_init_plan(scan: &TechScanResult) -> InitPlan {
    let mode = if scan.ai_governance.agents_md.is_some() {
        InitMode::Enhance
    } else {
        InitMode::Fresh
    };

    let rules = generate_rules(scan);
    let files = generate_files(scan, &rules, &mode);

    InitPlan {
        scan_result: scan.clone(),
        mode,
        rules,
        files,
    }
}

/// Write accepted files to disk.
pub fn execute_init_plan(root: &Path, plan: &InitPlan) -> Result<Vec<String>, InitError> {
    if !root.exists() {
        return Err(InitError::PathNotFound(root.display().to_string()));
    }

    let mut written = Vec::new();

    for file in &plan.files {
        let target = root.join(&file.rel_path);

        // Skip if file exists and overwrite is false
        if target.exists() && !file.overwrite {
            continue;
        }

        // Create parent directories
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(&target, &file.content)?;
        written.push(file.rel_path.clone());
        tracing::info!("Generated: {}", file.rel_path);
    }

    Ok(written)
}

// --- Rule generation engine ---

fn generate_rules(scan: &TechScanResult) -> Vec<GeneratedRule> {
    let mut rules = Vec::new();
    let mut id_counter = 0u32;

    let mut next_id = || -> String {
        id_counter += 1;
        format!("rule_{:03}", id_counter)
    };

    // 1. Rules from linter configs (skip items already enforced by tools)
    for tool in &scan.tools {
        let tool_rules = rules_from_tool(tool);
        for (content, skip) in tool_rules {
            if skip {
                continue; // Already enforced by tool, no need to document
            }
            rules.push(GeneratedRule {
                id: next_id(),
                category: RuleCategory::Linter,
                content,
                source: RuleSource::LinterConfig(tool.config_file.clone()),
                accepted: true,
            });
        }
    }

    // 2. Rules from tech stack
    for lang in &scan.languages {
        for rule in rules_for_language(lang) {
            rules.push(GeneratedRule {
                id: next_id(),
                category: RuleCategory::TechStack,
                content: rule,
                source: RuleSource::TechStackDetection,
                accepted: true,
            });
        }
    }

    for fw in &scan.frameworks {
        for rule in rules_for_framework(fw) {
            rules.push(GeneratedRule {
                id: next_id(),
                category: RuleCategory::TechStack,
                content: rule,
                source: RuleSource::FrameworkBestPractice,
                accepted: true,
            });
        }
    }

    // 3. Rules from directory structure
    for rule in rules_from_dir_structure(&scan.dir_structure) {
        rules.push(GeneratedRule {
            id: next_id(),
            category: RuleCategory::Directory,
            content: rule,
            source: RuleSource::DirectoryStructure,
            accepted: true,
        });
    }

    // 4. Rules from git log patterns
    if scan.git_stats.fix_commits >= 3 {
        rules.push(GeneratedRule {
            id: next_id(),
            category: RuleCategory::GitPattern,
            content: format!(
                "项目近期有 {} 个 fix commit，请特别注意代码质量和边界情况处理。",
                scan.git_stats.fix_commits
            ),
            source: RuleSource::GitLogAnalysis,
            accepted: true,
        });
    }

    for pattern in &scan.git_stats.recent_fix_patterns {
        let lower = pattern.to_lowercase();
        if lower.contains("timeout") || lower.contains("超时") {
            rules.push(GeneratedRule {
                id: next_id(),
                category: RuleCategory::GitPattern,
                content: "所有外部调用（HTTP、数据库、RPC）必须设置超时时间。".into(),
                source: RuleSource::GitLogAnalysis,
                accepted: true,
            });
            break;
        }
    }

    for pattern in &scan.git_stats.recent_fix_patterns {
        let lower = pattern.to_lowercase();
        if lower.contains("null") || lower.contains("undefined") || lower.contains("unwrap") {
            rules.push(GeneratedRule {
                id: next_id(),
                category: RuleCategory::GitPattern,
                content: "注意空值/None/undefined 的处理，禁止在生产路径中使用 unwrap() 或未检查的 nullable 访问。".into(),
                source: RuleSource::GitLogAnalysis,
                accepted: true,
            });
            break;
        }
    }

    rules
}

fn rules_from_tool(tool: &ToolConfig) -> Vec<(String, bool)> {
    match tool.name.as_str() {
        "eslint" => vec![
            ("代码必须通过 ESLint 检查。".into(), true),
        ],
        "prettier" => vec![
            ("代码格式由 Prettier 统一管理，无需手动格式化。".into(), true),
        ],
        "clippy" => vec![
            ("Rust 代码必须通过 clippy 检查，修复所有 warning。".into(), false),
        ],
        "typescript-strict" => vec![
            ("TypeScript 使用 strict 模式，禁止 any 类型（除非有明确注释说明原因）。".into(), false),
        ],
        "golangci-lint" => vec![
            ("Go 代码必须通过 golangci-lint 检查。".into(), true),
        ],
        "ruff" => vec![
            ("Python 代码格式和 lint 由 Ruff 统一管理。".into(), true),
        ],
        "black" => vec![
            ("Python 代码格式由 Black 统一管理，无需手动格式化。".into(), true),
        ],
        "mypy" => vec![
            ("Python 代码必须通过 mypy 类型检查。".into(), false),
        ],
        "flake8" => vec![
            ("Python 代码必须通过 Flake8 检查。".into(), true),
        ],
        "checkstyle" => vec![
            ("Java 代码必须通过 Checkstyle 风格检查。".into(), true),
        ],
        "spotbugs" => vec![
            ("Java 代码必须通过 SpotBugs 静态分析。".into(), false),
        ],
        "swiftlint" => vec![
            ("Swift 代码必须通过 SwiftLint 检查。".into(), true),
        ],
        "ktlint" => vec![
            ("Kotlin 代码格式由 ktlint 统一管理。".into(), true),
        ],
        "detekt" => vec![
            ("Kotlin 代码必须通过 detekt 静态分析。".into(), false),
        ],
        "rubocop" => vec![
            ("Ruby 代码必须通过 RuboCop 检查。".into(), true),
        ],
        "phpstan" => vec![
            ("PHP 代码必须通过 PHPStan 静态分析。".into(), false),
        ],
        "php-cs-fixer" => vec![
            ("PHP 代码格式由 PHP-CS-Fixer 统一管理。".into(), true),
        ],
        "dotnet-analyzers" => vec![
            ("C# 代码必须通过 .NET Analyzers 检查。".into(), false),
        ],
        _ => vec![],
    }
}

fn rules_for_language(lang: &Language) -> Vec<String> {
    match lang {
        Language::Rust => vec![
            "Rust 后端必须使用 `thiserror` 定义错误类型，禁止 `unwrap()` 出现在生产路径中（测试除外）。".into(),
            "使用 `tracing` 进行日志记录，禁止 `println!` 用于调试输出。".into(),
        ],
        Language::TypeScript => vec![
            "优先使用 TypeScript 的类型系统，避免 `as any` 类型断言。".into(),
            "使用 `const` 声明变量，仅在必要时使用 `let`，禁止 `var`。".into(),
        ],
        Language::JavaScript => vec![
            "使用 `const` 声明变量，仅在必要时使用 `let`，禁止 `var`。".into(),
        ],
        Language::Python => vec![
            "使用类型注解（Type Hints），所有公共函数必须有参数和返回值类型标注。".into(),
            "使用 f-string 格式化字符串，禁止 `%` 和 `.format()` 方式。".into(),
        ],
        Language::Go => vec![
            "错误必须显式处理，禁止忽略 error 返回值（`_ = err`）。".into(),
            "使用 `context.Context` 传递请求级信息和超时。".into(),
            "导出函数必须有 GoDoc 注释。".into(),
        ],
        Language::Java => vec![
            "所有公共类和方法必须有 Javadoc 注释。".into(),
            "使用 `Optional<T>` 替代返回 `null`，避免 NullPointerException。".into(),
            "异常处理：捕获具体异常类型，禁止 `catch (Exception e)` 吞掉所有异常。".into(),
            "使用 SLF4J + Logback 进行日志记录，禁止 `System.out.println`。".into(),
        ],
        Language::Swift => vec![
            "优先使用 `let`（不可变），仅在必要时使用 `var`。".into(),
            "使用 `guard` 提前返回，避免深层嵌套。".into(),
            "错误处理使用 `do-catch` 或 `Result<T, Error>`，禁止强制解包 `!`（测试除外）。".into(),
            "遵循 Swift API Design Guidelines 的命名约定。".into(),
        ],
        Language::Kotlin => vec![
            "优先使用 `val`（不可变），仅在必要时使用 `var`。".into(),
            "使用数据类（`data class`）表示纯数据对象。".into(),
            "空安全：使用 `?.` 和 `?:` 操作符，禁止 `!!`（测试除外）。".into(),
            "协程：使用结构化并发（`coroutineScope`），禁止全局 `GlobalScope`。".into(),
        ],
        Language::CSharp => vec![
            "使用 `async/await` 进行异步操作，禁止 `.Result` 或 `.Wait()` 阻塞。".into(),
            "使用 nullable reference types（`#nullable enable`），显式标注可空性。".into(),
            "遵循 .NET 命名约定：PascalCase 用于公共成员，camelCase 用于私有字段。".into(),
        ],
        Language::Ruby => vec![
            "遵循 Ruby Style Guide，方法命名使用 `snake_case`。".into(),
            "使用 `frozen_string_literal: true` 魔法注释提升性能。".into(),
            "优先使用符号（Symbol）而非字符串作为 Hash 键。".into(),
        ],
        Language::Php => vec![
            "遵循 PSR-12 编码规范。".into(),
            "使用严格类型声明：`declare(strict_types=1)`。".into(),
            "所有类必须使用命名空间，遵循 PSR-4 自动加载规范。".into(),
            "使用类型声明（参数类型 + 返回类型），PHP 8.0+ 使用 union types。".into(),
        ],
        _ => vec![],
    }
}

fn rules_for_framework(fw: &Framework) -> Vec<String> {
    match fw {
        Framework::React => vec![
            "使用函数组件 + Hooks，禁止 class component。".into(),
            "组件文件使用 PascalCase 命名（如 `MyComponent.tsx`）。".into(),
        ],
        Framework::Tauri => vec![
            "Tauri IPC 调用统一封装为 hook 或 service 层，禁止在组件中直接裸调 `invoke`。".into(),
            "后端 Tauri command 必须添加 `rename_all = \"snake_case\"` 保持前后端参数命名一致。".into(),
        ],
        Framework::Vue => vec![
            "使用 Composition API（`<script setup>`），避免 Options API。".into(),
        ],
        Framework::NextJs => vec![
            "页面组件放在 `app/` 或 `pages/` 目录下，API 路由放在 `api/` 目录。".into(),
        ],
        Framework::Express | Framework::Fastify => vec![
            "所有路由处理函数必须包含错误处理中间件。".into(),
            "API 接口必须进行参数校验。".into(),
        ],
        Framework::Django => vec![
            "使用 Django ORM 进行数据库操作，避免原始 SQL。".into(),
        ],
        Framework::FastApi => vec![
            "使用 Pydantic 模型定义请求/响应 Schema。".into(),
        ],
        Framework::Gin => vec![
            "中间件链中必须包含 Recovery 和 Logger，路由按业务模块分组。".into(),
        ],
        Framework::Echo => vec![
            "中间件按职责分层（认证、日志、恢复），使用 `e.Use()` 注册。".into(),
        ],
        Framework::Fiber => vec![
            "注意 Fiber 基于 fasthttp，与标准 `net/http` API 不完全兼容。".into(),
        ],
        Framework::Chi => vec![
            "使用标准库 `http.Handler` 接口，保持与 `net/http` 兼容。".into(),
        ],
        Framework::Kratos => vec![
            "遵循 Kratos 分层架构：api / service / biz / data，使用 Protobuf 定义接口。".into(),
        ],
        Framework::Spring => vec![
            "使用构造函数注入（`@RequiredArgsConstructor`），禁止字段注入（`@Autowired` on field）。".into(),
        ],
        Framework::Quarkus => vec![
            "使用 CDI（`@Inject`）进行依赖注入，REST 端点使用 JAX-RS 注解。".into(),
        ],
        Framework::Micronaut => vec![
            "使用编译时依赖注入，避免运行时反射。".into(),
        ],
        Framework::Rails => vec![
            "数据库变更必须通过 Migration，禁止手动修改 `schema.rb`。".into(),
        ],
        Framework::Laravel => vec![
            "控制器保持精简，业务逻辑放在 Service / Action 类，敏感配置使用 `.env`。".into(),
        ],
        Framework::SwiftUI => vec![
            "复杂业务逻辑抽到 ViewModel（MVVM），视图层保持轻量。".into(),
        ],
        Framework::UIKit => vec![
            "使用 Auto Layout 约束进行布局，ViewController 保持精简。".into(),
        ],
        Framework::JetpackCompose => vec![
            "遵循单向数据流（State hoisting），使用 ViewModel + StateFlow 管理状态。".into(),
        ],
        Framework::Flutter => vec![
            "Widget 保持精简，复杂逻辑抽到 BLoC / Provider / Riverpod。".into(),
        ],
        Framework::Dotnet => vec![
            "使用依赖注入（`IServiceCollection`），禁止 `new` 实例化服务类。".into(),
        ],
        _ => vec![],
    }
}

fn rules_from_dir_structure(dir: &DirStructure) -> Vec<String> {
    let mut rules = Vec::new();

    if dir.has_src {
        rules.push("所有业务逻辑代码必须放在 `src/` 目录下，保持目录结构清晰。".into());
    }

    rules
}

use crate::services::tech_detector::DirStructure;

/// Regenerate files from a (potentially user-edited) plan.
pub fn generate_files_from_plan(plan: &InitPlan) -> Vec<GeneratedFile> {
    generate_files(&plan.scan_result, &plan.rules, &plan.mode)
}

// --- File generation ---

fn generate_files(scan: &TechScanResult, rules: &[GeneratedRule], mode: &InitMode) -> Vec<GeneratedFile> {
    let mut files = Vec::new();

    // 1. AGENTS.md
    let agents_content = generate_agents_md(scan, rules, mode);
    let agents_exists = scan.ai_governance.agents_md.is_some();
    files.push(GeneratedFile {
        rel_path: "AGENTS.md".into(),
        content: agents_content,
        description: if agents_exists {
            "AI 编码宪法（增强建议追加到末尾）".into()
        } else {
            "AI 编码宪法（全新生成）".into()
        },
        overwrite: !agents_exists, // fresh mode: create; enhance mode: don't overwrite
    });

    // 2. .ai/progress.md (only if not exists)
    if scan.ai_governance.progress_md.is_none() {
        let progress_content = generate_progress_md(scan);
        files.push(GeneratedFile {
            rel_path: ".ai/progress.md".into(),
            content: progress_content,
            description: "当前任务追踪文件（空模板）".into(),
            overwrite: false,
        });
    }

    // 3. .docguardian.toml
    let config_content = generate_config_toml(scan);
    files.push(GeneratedFile {
        rel_path: ".docguardian.toml".into(),
        content: config_content,
        description: "DocGuardian 项目配置文件".into(),
        overwrite: false,
    });

    files
}

fn generate_agents_md(scan: &TechScanResult, rules: &[GeneratedRule], mode: &InitMode) -> String {
    let accepted_rules: Vec<&GeneratedRule> = rules.iter().filter(|r| r.accepted).collect();

    let mut md = String::new();

    match mode {
        InitMode::Fresh => {
            // ── Header ──
            md.push_str(&format!("# {} — AI 编码宪法\n\n", scan.project_name));
            md.push_str(&format!(
                "> 由 DocGuardian 自动生成 · {}\n\n",
                chrono::Local::now().format("%Y-%m-%d")
            ));
            md.push_str("---\n\n");

            // ── §1 Project Overview ──
            md.push_str("## 项目概述\n\n");
            let lang_strs: Vec<String> = scan.languages.iter().map(|l| format!("{:?}", l)).collect();
            let fw_strs: Vec<String> = scan.frameworks.iter().map(|f| format!("{:?}", f)).collect();
            md.push_str(&format!(
                "**技术栈**: {}{}\n\n",
                if lang_strs.is_empty() { "未知语言".to_string() } else { lang_strs.join(", ") },
                if fw_strs.is_empty() { String::new() } else { format!(", {}", fw_strs.join(", ")) }
            ));
            md.push_str("<!-- TODO: 请补充项目简介（一句话描述项目解决什么问题） -->\n\n");

            // ── §2 Build & Test Commands ──
            md.push_str("## 构建与测试\n\n");
            md.push_str("```bash\n");
            let build_cmds = build_commands_for_scan(scan);
            for cmd in &build_cmds {
                md.push_str(&format!("{}\n", cmd));
            }
            md.push_str("```\n\n");

            // ── §3 Three-tier Boundaries (Always / Ask First / Never) ──
            md.push_str("## 行为边界\n\n");
            let boundaries = boundaries_for_scan(scan);
            md.push_str("### ✅ 始终执行\n\n");
            for line in &boundaries.always {
                md.push_str(&format!("- {}\n", line));
            }
            md.push_str("\n### ⚠️ 先询问再执行\n\n");
            for line in &boundaries.ask_first {
                md.push_str(&format!("- {}\n", line));
            }
            md.push_str("\n### 🚫 禁止执行\n\n");
            for line in &boundaries.never {
                md.push_str(&format!("- {}\n", line));
            }
            md.push('\n');

            // ── §4 Tech Stack Constraints ──
            let tech_rules: Vec<&&GeneratedRule> = accepted_rules
                .iter()
                .filter(|r| matches!(r.category, RuleCategory::TechStack))
                .collect();
            if !tech_rules.is_empty() {
                md.push_str("## 技术栈约束\n\n");
                for rule in tech_rules {
                    md.push_str(&format!("- {}\n", rule.content));
                }
                md.push('\n');
            }

            // ── §5 Toolchain Constraints ──
            let linter_rules: Vec<&&GeneratedRule> = accepted_rules
                .iter()
                .filter(|r| matches!(r.category, RuleCategory::Linter))
                .collect();
            if !linter_rules.is_empty() {
                md.push_str("## 工具链约束\n\n");
                for rule in linter_rules {
                    md.push_str(&format!("- {}\n", rule.content));
                }
                md.push('\n');
            }

            // ── §6 Directory Structure + Key File Pointers ──
            md.push_str("## 目录结构\n\n");
            md.push_str("```\n");
            let dir_lines = dir_tree_for_scan(scan);
            for line in &dir_lines {
                md.push_str(&format!("{}\n", line));
            }
            md.push_str("```\n\n");
            // Directory-derived rules
            let dir_rules: Vec<&&GeneratedRule> = accepted_rules
                .iter()
                .filter(|r| matches!(r.category, RuleCategory::Directory))
                .collect();
            if !dir_rules.is_empty() {
                for rule in dir_rules {
                    md.push_str(&format!("- {}\n", rule.content));
                }
                md.push('\n');
            }
            // Key file pointers
            let key_files = key_file_pointers_for_scan(scan);
            if !key_files.is_empty() {
                md.push_str("**关键文件索引**（修改相关功能时优先查看）：\n\n");
                for (file, desc) in &key_files {
                    md.push_str(&format!("- `{}` — {}\n", file, desc));
                }
                md.push('\n');
            }

            // ── §7 Code Examples (Good vs Bad) ──
            let examples = code_examples_for_scan(scan);
            if !examples.is_empty() {
                md.push_str("## 代码示例\n\n");
                md.push_str("> AI 应该模仿 ✅ 风格，避免 ❌ 风格。\n\n");
                for example in &examples {
                    md.push_str(&format!("{}\n\n", example));
                }
            }

            // ── §8 Testing Guidelines ──
            md.push_str("## 测试指南\n\n");
            let test_lines = testing_guidelines_for_scan(scan);
            for line in &test_lines {
                md.push_str(&format!("- {}\n", line));
            }
            md.push('\n');

            // ── §9 Git-derived patterns ──
            let git_rules: Vec<&&GeneratedRule> = accepted_rules
                .iter()
                .filter(|r| matches!(r.category, RuleCategory::GitPattern))
                .collect();
            if !git_rules.is_empty() {
                md.push_str("## 从项目历史推断的约束\n\n");
                for rule in git_rules {
                    md.push_str(&format!("- {}\n", rule.content));
                }
                md.push('\n');
            }

            // ── §10 Common Mistakes (placeholder for iteration) ──
            md.push_str("## 常犯错误\n\n");
            md.push_str("> 每当 AI 犯错时，在此记录一条规则。这是 AGENTS.md 中 ROI 最高的章节。\n\n");
            let common_mistakes = common_mistakes_for_scan(scan);
            for mistake in &common_mistakes {
                md.push_str(&format!("- {}\n", mistake));
            }
            md.push_str("<!-- 迭代添加：当 AI 重复犯同一错误时，在此追加一条规则 -->\n\n");

            // ── §11 TODO placeholder ──
            md.push_str("## 待补充\n\n");
            md.push_str("<!-- TODO: 请根据项目实际情况补充以下内容 -->\n");
            md.push_str("<!-- - 业务领域特有约束 -->\n");
            md.push_str("<!-- - 架构决策记录（为什么选择这个技术栈） -->\n");
        }
        InitMode::Enhance => {
            md.push_str(&format!(
                "\n\n---\n\n## DocGuardian 增强建议（{}）\n\n",
                chrono::Local::now().format("%Y-%m-%d")
            ));
            md.push_str("> 以下规则由 DocGuardian 扫描项目后自动生成，请逐条审阅。\n\n");
            for rule in &accepted_rules {
                md.push_str(&format!("- {}\n", rule.content));
            }
        }
    }

    md
}

/// Generate build/test commands based on detected tech stack
fn build_commands_for_scan(scan: &TechScanResult) -> Vec<String> {
    let mut cmds = Vec::new();

    // Package manager detection
    let has_pnpm = scan.dir_structure.top_level_dirs.iter().any(|d| d == "pnpm-lock.yaml")
        || scan.tools.iter().any(|t| t.name == "pnpm");
    let pm = if has_pnpm { "pnpm" } else { "npm" };

    // JS/TS project
    if scan.languages.iter().any(|l| matches!(l, Language::TypeScript | Language::JavaScript)) {
        cmds.push(format!("# 安装依赖"));
        cmds.push(format!("{} install", pm));
    }

    // Tauri project
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri)) {
        cmds.push(format!("# 开发模式"));
        cmds.push(format!("cargo tauri dev"));
        cmds.push(format!("# 构建"));
        cmds.push(format!("{} run build && cargo tauri build", pm));
    } else if scan.languages.iter().any(|l| matches!(l, Language::TypeScript | Language::JavaScript)) {
        cmds.push(format!("# 开发模式"));
        cmds.push(format!("{} run dev", pm));
        cmds.push(format!("# 构建"));
        cmds.push(format!("{} run build", pm));
    }

    // Rust standalone
    if scan.languages.iter().any(|l| matches!(l, Language::Rust))
        && !scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri))
    {
        cmds.push("# 构建".into());
        cmds.push("cargo build".into());
        cmds.push("# 测试".into());
        cmds.push("cargo test".into());
    }

    // Rust inside Tauri
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri)) {
        cmds.push("# Rust 测试".into());
        cmds.push("cd src-tauri && cargo test".into());
    }

    // Python
    if scan.languages.iter().any(|l| matches!(l, Language::Python)) {
        cmds.push("# 安装依赖".into());
        cmds.push("pip install -r requirements.txt".into());
        cmds.push("# 测试".into());
        cmds.push("pytest".into());
    }

    // Go
    if scan.languages.iter().any(|l| matches!(l, Language::Go)) {
        cmds.push("# 构建".into());
        cmds.push("go build ./...".into());
        cmds.push("# 测试".into());
        cmds.push("go test ./...".into());
        if scan.tools.iter().any(|t| t.name == "golangci-lint") {
            cmds.push("# Lint".into());
            cmds.push("golangci-lint run".into());
        }
    }

    // Java
    if scan.languages.iter().any(|l| matches!(l, Language::Java)) {
        if scan.dir_structure.top_level_dirs.iter().any(|d| d == "pom.xml") || std::path::Path::new(&scan.root_path).join("pom.xml").exists() {
            cmds.push("# 构建 (Maven)".into());
            cmds.push("mvn clean package".into());
            cmds.push("# 测试".into());
            cmds.push("mvn test".into());
        } else {
            cmds.push("# 构建 (Gradle)".into());
            cmds.push("./gradlew build".into());
            cmds.push("# 测试".into());
            cmds.push("./gradlew test".into());
        }
    }

    // Swift
    if scan.languages.iter().any(|l| matches!(l, Language::Swift)) {
        if scan.frameworks.iter().any(|f| matches!(f, Framework::SwiftUI | Framework::UIKit)) {
            cmds.push("# 构建 (Xcode)".into());
            cmds.push("xcodebuild -scheme <SCHEME> -sdk iphonesimulator build".into());
            cmds.push("# 测试".into());
            cmds.push("xcodebuild -scheme <SCHEME> -sdk iphonesimulator test".into());
        } else {
            cmds.push("# 构建 (Swift Package)".into());
            cmds.push("swift build".into());
            cmds.push("# 测试".into());
            cmds.push("swift test".into());
        }
    }

    // Kotlin (standalone / Android)
    if scan.languages.iter().any(|l| matches!(l, Language::Kotlin))
        && !scan.languages.iter().any(|l| matches!(l, Language::Java))
    {
        cmds.push("# 构建 (Gradle)".into());
        cmds.push("./gradlew build".into());
        cmds.push("# 测试".into());
        cmds.push("./gradlew test".into());
    }

    // C#
    if scan.languages.iter().any(|l| matches!(l, Language::CSharp)) {
        cmds.push("# 构建".into());
        cmds.push("dotnet build".into());
        cmds.push("# 测试".into());
        cmds.push("dotnet test".into());
    }

    // Ruby
    if scan.languages.iter().any(|l| matches!(l, Language::Ruby)) {
        cmds.push("# 安装依赖".into());
        cmds.push("bundle install".into());
        if scan.frameworks.iter().any(|f| matches!(f, Framework::Rails)) {
            cmds.push("# 开发模式".into());
            cmds.push("rails server".into());
            cmds.push("# 测试".into());
            cmds.push("bundle exec rspec".into());
        } else {
            cmds.push("# 测试".into());
            cmds.push("bundle exec rake test".into());
        }
    }

    // PHP
    if scan.languages.iter().any(|l| matches!(l, Language::Php)) {
        cmds.push("# 安装依赖".into());
        cmds.push("composer install".into());
        if scan.frameworks.iter().any(|f| matches!(f, Framework::Laravel)) {
            cmds.push("# 开发模式".into());
            cmds.push("php artisan serve".into());
            cmds.push("# 测试".into());
            cmds.push("php artisan test".into());
        } else {
            cmds.push("# 测试".into());
            cmds.push("./vendor/bin/phpunit".into());
        }
    }

    // Lint commands
    if scan.tools.iter().any(|t| t.name == "eslint") {
        cmds.push(format!("# Lint"));
        cmds.push(format!("{} run lint", pm));
    }
    if scan.tools.iter().any(|t| t.name == "clippy") {
        cmds.push("# Rust lint".into());
        cmds.push("cargo clippy -- -D warnings".into());
    }
    if scan.tools.iter().any(|t| t.name == "ruff") {
        cmds.push("# Python lint + format".into());
        cmds.push("ruff check . && ruff format .".into());
    }
    if scan.tools.iter().any(|t| t.name == "mypy") {
        cmds.push("# 类型检查".into());
        cmds.push("mypy .".into());
    }
    if scan.tools.iter().any(|t| t.name == "rubocop") {
        cmds.push("# Ruby lint".into());
        cmds.push("rubocop".into());
    }
    if scan.tools.iter().any(|t| t.name == "phpstan") {
        cmds.push("# PHP 静态分析".into());
        cmds.push("./vendor/bin/phpstan analyse".into());
    }
    if scan.tools.iter().any(|t| t.name == "swiftlint") {
        cmds.push("# Swift lint".into());
        cmds.push("swiftlint".into());
    }

    if cmds.is_empty() {
        cmds.push("# TODO: 请补充构建和测试命令".into());
    }

    cmds
}

/// Generate a simplified directory tree from scan results
fn dir_tree_for_scan(scan: &TechScanResult) -> Vec<String> {
    let mut lines = Vec::new();
    lines.push(format!("{}/", scan.project_name));

    // Show top-level dirs, filtered
    let skip = ["node_modules", "dist", "target", ".git", "__pycache__", ".next", "build"];
    let mut shown: Vec<&String> = scan.dir_structure.top_level_dirs
        .iter()
        .filter(|d| !skip.contains(&d.as_str()))
        .collect();
    shown.sort();

    for (i, dir) in shown.iter().enumerate() {
        let is_last = i == shown.len() - 1
            && scan.ai_governance.agents_md.is_none()
            && scan.ai_governance.progress_md.is_none();
        let prefix = if is_last { "└── " } else { "├── " };
        let annotation = dir_annotation(dir, scan);
        if annotation.is_empty() {
            lines.push(format!("{}{}/ ", prefix, dir));
        } else {
            lines.push(format!("{}{}/ {}", prefix, dir, annotation));
        }
    }

    // Key files at root
    if scan.ai_governance.agents_md.is_some() || true {
        lines.push("├── AGENTS.md".into());
    }
    lines.push("└── .docguardian.toml".into());

    lines
}

fn dir_annotation(dir: &str, scan: &TechScanResult) -> String {
    // Provide helpful annotations for common directories
    let is_tauri = scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri));
    let is_react = scan.frameworks.iter().any(|f| matches!(f, Framework::React));

    match dir {
        "src" if is_react => "# React 前端源码".into(),
        "src" => "# 源码".into(),
        "src-tauri" if is_tauri => "# Tauri/Rust 后端".into(),
        "docs" => "# 文档".into(),
        "tests" | "test" | "__tests__" => "# 测试".into(),
        "public" => "# 静态资源".into(),
        "scripts" => "# 脚本".into(),
        ".github" => "# CI/CD".into(),
        ".ai" => "# AI 状态文件（progress.md）".into(),
        _ => String::new(),
    }
}

/// Generate testing guidelines based on detected tech stack
fn testing_guidelines_for_scan(scan: &TechScanResult) -> Vec<String> {
    let mut lines = Vec::new();

    lines.push("新增功能必须附带对应的测试用例。".into());

    for lang in &scan.languages {
        match lang {
            Language::Rust => {
                lines.push("Rust 测试使用 `#[test]` 宏，集成测试放在 `tests/` 目录。".into());
                lines.push("运行 `cargo test -- --nocapture` 查看测试输出。".into());
            }
            Language::TypeScript | Language::JavaScript => {
                lines.push("前端测试优先使用组件级测试，验证用户交互流程。".into());
            }
            Language::Python => {
                lines.push("使用 `pytest` 运行测试，测试文件命名 `test_*.py`。".into());
                lines.push("使用 `pytest-cov` 追踪覆盖率。".into());
            }
            Language::Go => {
                lines.push("测试文件命名 `*_test.go`，使用 `go test ./...` 运行。".into());
                lines.push("使用 `testify` 或标准库 `testing` 包，表格驱动测试优先。".into());
                lines.push("覆盖率：`go test -coverprofile=coverage.out ./...`。".into());
            }
            Language::Java => {
                lines.push("使用 JUnit 5（`@Test`）编写测试，放在 `src/test/java/` 目录。".into());
                lines.push("使用 Mockito 进行 Mock，`@MockBean` 用于 Spring 集成测试。".into());
                lines.push("命名约定：`[ClassName]Test.java`，方法名描述行为（`shouldXxxWhenYyy`）。".into());
            }
            Language::Swift => {
                lines.push("使用 XCTest 框架编写测试，测试文件放在 `Tests/` 目录。".into());
                lines.push("UI 测试使用 `XCUITest`，单元测试使用 `XCTestCase`。".into());
            }
            Language::Kotlin => {
                lines.push("使用 JUnit 5 + MockK 编写测试。".into());
                lines.push("Android UI 测试使用 Espresso 或 Compose Testing。".into());
            }
            Language::CSharp => {
                lines.push("使用 xUnit / NUnit 编写测试，放在独立的 `.Tests` 项目中。".into());
                lines.push("使用 Moq 或 NSubstitute 进行 Mock。".into());
            }
            Language::Ruby => {
                lines.push("使用 RSpec 编写测试，测试文件放在 `spec/` 目录。".into());
                lines.push("Rails 项目使用 FactoryBot 创建测试数据。".into());
            }
            Language::Php => {
                lines.push("使用 PHPUnit 编写测试，测试文件放在 `tests/` 目录。".into());
                lines.push("Laravel 项目使用 `php artisan test` 运行测试。".into());
            }
            _ => {}
        }
    }

    if scan.dir_structure.has_ci {
        lines.push("所有代码变更必须通过 CI 检查后才能合并。".into());
    }

    lines
}

/// Three-tier behavior boundaries: Always / Ask First / Never
struct Boundaries {
    always: Vec<String>,
    ask_first: Vec<String>,
    never: Vec<String>,
}

fn boundaries_for_scan(scan: &TechScanResult) -> Boundaries {
    let mut always = vec![
        "修改文件后运行对应的 lint 和类型检查".into(),
        "新增功能时编写或更新测试".into(),
    ];
    let mut ask_first = vec![
        "添加新的生产依赖（npm/cargo add）".into(),
        "修改数据库 schema 或迁移文件".into(),
        "删除文件或目录".into(),
    ];
    let mut never = vec![
        "在代码中硬编码 API Key、密码或 token".into(),
        "修改 `node_modules/`、`target/`、`dist/` 等生成目录".into(),
        "在未经确认的情况下删除用户数据".into(),
    ];

    // Framework-specific
    for fw in &scan.frameworks {
        match fw {
            Framework::Tauri => {
                always.push("Tauri command 参数使用 `rename_all = \"snake_case\"`".into());
                ask_first.push("修改 Tauri capabilities/permissions 配置".into());
                never.push("自动执行 `git commit`（除非用户显式启用 `auto_commit`）".into());
            }
            Framework::React => {
                always.push("组件文件使用 PascalCase 命名".into());
            }
            Framework::NextJs => {
                ask_first.push("修改 `next.config.js` 或中间件配置".into());
            }
            Framework::Django => {
                ask_first.push("修改 `settings.py` 或创建数据迁移".into());
            }
            _ => {}
        }
    }

    // Language-specific
    for lang in &scan.languages {
        match lang {
            Language::Rust => {
                never.push("在生产代码路径中使用 `unwrap()`（测试除外）".into());
                never.push("使用 `println!` 调试（应使用 `tracing`）".into());
            }
            Language::TypeScript => {
                never.push("使用 `any` 类型（除非有明确注释说明原因）".into());
                never.push("使用 `var` 声明变量".into());
            }
            Language::Go => {
                never.push("忽略 error 返回值（`_ = err`）".into());
                never.push("使用 `panic` 替代错误返回（库代码中）".into());
                ask_first.push("修改 `go.mod` 中的依赖版本".into());
            }
            Language::Java => {
                never.push("使用 `System.out.println` 调试（应使用 SLF4J）".into());
                never.push("捕获 `Exception` 或 `Throwable` 后不做任何处理".into());
                ask_first.push("修改数据库 Migration 或 Flyway 脚本".into());
            }
            Language::Swift => {
                never.push("在生产代码中使用强制解包 `!`（测试除外）".into());
                never.push("使用 `try!` 或 `as!` 强制转换".into());
                ask_first.push("修改 Xcode 项目配置或 signing 设置".into());
            }
            Language::Kotlin => {
                never.push("使用 `!!` 强制非空断言（测试除外）".into());
                never.push("使用 `GlobalScope` 启动协程".into());
                ask_first.push("修改 ProGuard / R8 混淆规则".into());
            }
            Language::CSharp => {
                never.push("使用 `.Result` 或 `.Wait()` 阻塞异步调用".into());
                ask_first.push("修改 `.csproj` 或 NuGet 包版本".into());
            }
            Language::Ruby => {
                never.push("使用 `eval` 执行动态代码".into());
                ask_first.push("修改 `Gemfile` 中的依赖版本".into());
            }
            Language::Php => {
                never.push("使用 `eval()` 或 `extract()` 函数".into());
                never.push("直接拼接 SQL 字符串（使用参数化查询）".into());
                ask_first.push("修改 `composer.json` 中的依赖版本".into());
            }
            _ => {}
        }
    }

    // CI
    if scan.dir_structure.has_ci {
        always.push("确保变更通过 CI 检查后才提交".into());
    }

    Boundaries { always, ask_first, never }
}

/// Key file pointers: helps AI navigate the codebase without exploration
fn key_file_pointers_for_scan(scan: &TechScanResult) -> Vec<(String, String)> {
    let mut pointers: Vec<(String, String)> = Vec::new();

    let is_tauri = scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri));
    let is_react = scan.frameworks.iter().any(|f| matches!(f, Framework::React));
    let is_nextjs = scan.frameworks.iter().any(|f| matches!(f, Framework::NextJs));

    // React / general frontend
    if is_react && !is_nextjs {
        pointers.push(("src/App.tsx".into(), "应用路由与页面入口".into()));
    }
    if is_nextjs {
        pointers.push(("app/layout.tsx".into(), "根布局与全局 provider".into()));
        pointers.push(("app/page.tsx".into(), "首页入口".into()));
    }

    // Tauri
    if is_tauri {
        pointers.push(("src-tauri/src/lib.rs".into(), "Tauri 应用入口与命令注册".into()));
        pointers.push(("src-tauri/src/commands/".into(), "所有 IPC 命令定义".into()));
        pointers.push(("src-tauri/capabilities/default.json".into(), "权限与能力配置".into()));
    }

    // Rust standalone
    if scan.languages.iter().any(|l| matches!(l, Language::Rust)) && !is_tauri {
        pointers.push(("src/main.rs".into(), "程序入口".into()));
        pointers.push(("src/lib.rs".into(), "库入口与模块导出".into()));
    }

    // Python
    if scan.languages.iter().any(|l| matches!(l, Language::Python)) {
        if scan.frameworks.iter().any(|f| matches!(f, Framework::Django)) {
            pointers.push(("manage.py".into(), "Django 管理入口".into()));
            pointers.push(("urls.py".into(), "URL 路由配置".into()));
        }
        if scan.frameworks.iter().any(|f| matches!(f, Framework::FastApi)) {
            pointers.push(("main.py".into(), "FastAPI 应用入口".into()));
        }
    }

    // Go
    if scan.languages.iter().any(|l| matches!(l, Language::Go)) {
        pointers.push(("go.mod".into(), "Go 模块定义与依赖管理".into()));
        pointers.push(("cmd/".into(), "应用入口（main 包）".into()));
        if scan.frameworks.iter().any(|f| matches!(f, Framework::Kratos)) {
            pointers.push(("api/".into(), "Protobuf API 定义".into()));
            pointers.push(("internal/biz/".into(), "业务逻辑层".into()));
            pointers.push(("internal/data/".into(), "数据访问层".into()));
            pointers.push(("internal/service/".into(), "服务实现层".into()));
        }
    }

    // Java / Spring
    if scan.languages.iter().any(|l| matches!(l, Language::Java)) {
        if scan.frameworks.iter().any(|f| matches!(f, Framework::Spring)) {
            pointers.push(("src/main/java/".into(), "Java 源码".into()));
            pointers.push(("src/main/resources/application.yml".into(), "Spring 配置".into()));
            pointers.push(("src/test/java/".into(), "测试代码".into()));
        }
        if std::path::Path::new(&scan.root_path).join("pom.xml").exists() {
            pointers.push(("pom.xml".into(), "Maven 项目配置与依赖".into()));
        } else {
            pointers.push(("build.gradle".into(), "Gradle 构建配置".into()));
        }
    }

    // Swift / iOS
    if scan.languages.iter().any(|l| matches!(l, Language::Swift)) {
        if scan.frameworks.iter().any(|f| matches!(f, Framework::SwiftUI | Framework::UIKit)) {
            pointers.push(("Info.plist".into(), "应用配置".into()));
        }
        pointers.push(("Package.swift".into(), "Swift Package 定义".into()));
    }

    // Kotlin / Android
    if scan.frameworks.iter().any(|f| matches!(f, Framework::JetpackCompose)) {
        pointers.push(("app/src/main/".into(), "Android 主源码".into()));
        pointers.push(("app/build.gradle.kts".into(), "应用级构建配置".into()));
    }

    // Ruby / Rails
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Rails)) {
        pointers.push(("config/routes.rb".into(), "路由配置".into()));
        pointers.push(("app/models/".into(), "ActiveRecord 模型".into()));
        pointers.push(("app/controllers/".into(), "控制器".into()));
        pointers.push(("db/migrate/".into(), "数据库迁移".into()));
    }

    // PHP / Laravel
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Laravel)) {
        pointers.push(("routes/web.php".into(), "Web 路由".into()));
        pointers.push(("routes/api.php".into(), "API 路由".into()));
        pointers.push(("app/Http/Controllers/".into(), "控制器".into()));
        pointers.push(("app/Models/".into(), "Eloquent 模型".into()));
        pointers.push(("database/migrations/".into(), "数据库迁移".into()));
    }

    // C# / .NET
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Dotnet)) {
        pointers.push(("Program.cs".into(), "应用入口与服务配置".into()));
        pointers.push(("appsettings.json".into(), "应用配置".into()));
    }

    // Flutter
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Flutter)) {
        pointers.push(("lib/main.dart".into(), "Flutter 应用入口".into()));
        pointers.push(("pubspec.yaml".into(), "依赖与项目配置".into()));
    }

    // Config files
    if scan.tools.iter().any(|t| t.name == "typescript-strict") {
        pointers.push(("tsconfig.json".into(), "TypeScript 编译配置".into()));
    }

    pointers
}

/// Code examples showing Good vs Bad patterns for detected tech stack
fn code_examples_for_scan(scan: &TechScanResult) -> Vec<String> {
    let mut examples = Vec::new();

    // Rust error handling
    if scan.languages.iter().any(|l| matches!(l, Language::Rust)) {
        examples.push(
            "**Rust 错误处理**\n\
             ```rust\n\
             // ✅ Good\n\
             fn read_config(path: &Path) -> Result<Config, AppError> {\n\
             \x20   let content = std::fs::read_to_string(path)\n\
             \x20       .map_err(|e| AppError::Io(e))?;\n\
             \x20   Ok(toml::from_str(&content)?)\n\
             }\n\
             \n\
             // ❌ Bad\n\
             fn read_config(path: &Path) -> Config {\n\
             \x20   let content = std::fs::read_to_string(path).unwrap();\n\
             \x20   toml::from_str(&content).unwrap()\n\
             }\n\
             ```".into()
        );
    }

    // TypeScript
    if scan.languages.iter().any(|l| matches!(l, Language::TypeScript)) {
        examples.push(
            "**TypeScript 类型安全**\n\
             ```typescript\n\
             // ✅ Good\n\
             const fetchUser = async (id: string): Promise<User> => {\n\
             \x20 const res = await api.get<User>(`/users/${id}`);\n\
             \x20 return res.data;\n\
             };\n\
             \n\
             // ❌ Bad\n\
             const fetchUser = async (id: any) => {\n\
             \x20 const res = await api.get('/users/' + id) as any;\n\
             \x20 return res.data;\n\
             };\n\
             ```".into()
        );
    }

    // Tauri IPC
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri)) {
        examples.push(
            "**Tauri IPC 调用**\n\
             ```typescript\n\
             // ✅ Good — 使用封装的 hook\n\
             const cmd = useTauriCommand<Project>(\"add_project\");\n\
             const result = await cmd.execute({ root_path: path });\n\
             \n\
             // ❌ Bad — 裸调 invoke\n\
             const result = await invoke(\"add_project\", { rootPath: path });\n\
             ```".into()
        );
    }

    // React
    if scan.frameworks.iter().any(|f| matches!(f, Framework::React)) {
        examples.push(
            "**React 组件**\n\
             ```tsx\n\
             // ✅ Good — 函数组件 + TypeScript props\n\
             interface Props { title: string; onClose: () => void }\n\
             function Modal({ title, onClose }: Props) {\n\
             \x20 return <div>...</div>;\n\
             }\n\
             \n\
             // ❌ Bad — class component + any\n\
             class Modal extends React.Component<any> { ... }\n\
             ```".into()
        );
    }

    // 其他语言的代码示例交给 LLM 智能层生成（更贴合项目上下文）

    examples
}

/// Seed common mistakes based on known tech-stack pitfalls
fn common_mistakes_for_scan(scan: &TechScanResult) -> Vec<String> {
    let mut mistakes = Vec::new();

    // Tauri-specific
    if scan.frameworks.iter().any(|f| matches!(f, Framework::Tauri)) {
        mistakes.push(
            "Tauri IPC 参数命名不一致：前端用 `snake_case`，后端 `#[tauri::command]` 默认期望 `camelCase`。\
             务必添加 `rename_all = \"snake_case\"`。".into()
        );
    }

    // Rust
    if scan.languages.iter().any(|l| matches!(l, Language::Rust)) {
        mistakes.push(
            "在 `async fn` 中使用 `std::fs` 同步 IO 会阻塞 tokio runtime。\
             对于重 IO 操作应使用 `tokio::fs` 或 `spawn_blocking`。".into()
        );
    }

    // React
    if scan.frameworks.iter().any(|f| matches!(f, Framework::React)) {
        mistakes.push(
            "`useEffect` 中缺少 cleanup 函数导致内存泄漏。订阅、定时器、异步操作都需要 cleanup。".into()
        );
    }

    // TypeScript
    if scan.languages.iter().any(|l| matches!(l, Language::TypeScript)) {
        mistakes.push(
            "导入路径使用相对路径 `../../` 过深。应使用 `@/` 路径别名保持导入清晰。".into()
        );
    }

    // Python
    if scan.languages.iter().any(|l| matches!(l, Language::Python)) {
        mistakes.push(
            "在函数参数默认值中使用可变对象（如 `def f(x=[])`），会导致所有调用共享同一实例。".into()
        );
    }

    // 其他语言的常犯错误交给 LLM 智能层生成（更贴合项目上下文）

    mistakes
}

fn generate_progress_md(scan: &TechScanResult) -> String {
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();
    let mut md = String::new();

    // Header
    md.push_str(&format!("# 项目进度追踪 (AI Session Progress)\n\n"));
    md.push_str("> **用途**: 跨会话记忆。每次 AI 会话结束前必须更新本文件。\n");
    md.push_str("> **格式**: 保持精简，仅记录关键状态。\n\n");

    // 当前状态
    md.push_str("## 当前状态\n\n");
    md.push_str(&format!("- **最后会话**: {}\n", today));
    md.push_str("- **最后完成**: 项目治理框架初始化\n");
    md.push_str("- **当前进行中**: 无\n\n");

    // 已完成里程碑
    md.push_str("## 已完成里程碑\n\n");
    md.push_str("| 日期 | 里程碑 | 关键变更 |\n");
    md.push_str("|:--|:--|:--|\n");

    // Auto-populate first milestone based on scan
    let techs: Vec<String> = scan.languages.iter().map(|l| format!("{:?}", l)).collect();
    let tech_str = if techs.is_empty() { "未知技术栈".to_string() } else { techs.join(", ") };
    md.push_str(&format!(
        "| {} | 治理框架初始化 | DocGuardian 生成 AGENTS.md，技术栈: {} |\n\n",
        today, tech_str
    ));

    md.push_str("> 更早期的里程碑已归档至 `.ai/archive/`，以保持本文件精简。\n\n");

    // 待办事项
    md.push_str("## 待办事项\n\n");
    md.push_str("- [x] 项目治理框架初始化（AGENTS.md + progress.md）\n");
    md.push_str("- [ ] <!-- 在此添加待办事项 -->\n\n");

    // 阻塞项
    md.push_str("## 阻塞项\n\n");
    md.push_str("| 任务 | 阻塞原因 | 等待谁 |\n");
    md.push_str("|:--|:--|:--|\n");
    md.push_str("| <!-- 无 --> | — | — |\n\n");

    // 关键决策
    md.push_str("## 关键决策\n\n");
    md.push_str("| 日期 | 决策 | 原因 |\n");
    md.push_str("|:--|:--|:--|\n");
    md.push_str(&format!(
        "| {} | 引入 AI 治理框架 | 规范 AI 编码助手行为，降低幻觉率 |\n\n",
        today
    ));

    // 已知技术债务
    md.push_str("## 已知技术债务\n\n");
    md.push_str("- <!-- 在此记录已知的技术债务 -->\n");

    md
}

fn generate_config_toml(scan: &TechScanResult) -> String {
    let has_cursorrules = scan.ai_governance.cursorrules.is_some();
    let has_windsurfrules = scan.ai_governance.windsurfrules.is_some();

    let mut rule_paths = vec!["\"AGENTS.md\"".to_string()];
    if has_cursorrules {
        rule_paths.push("\".cursorrules\"".to_string());
    }
    if has_windsurfrules {
        rule_paths.push("\".windsurfrules\"".to_string());
    }

    // Detect tech stack summary for comment
    let techs: Vec<String> = scan.languages.iter().map(|l| format!("{:?}", l)).collect();
    let fws: Vec<String> = scan.frameworks.iter().map(|f| format!("{:?}", f)).collect();
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let mut toml = String::new();

    // Header comment
    toml.push_str(&format!("# DocGuardian 项目配置\n"));
    toml.push_str(&format!("# 生成日期: {}\n", today));
    toml.push_str(&format!("# 技术栈: {}\n", if techs.is_empty() { "未知".to_string() } else { techs.join(", ") }));
    if !fws.is_empty() {
        toml.push_str(&format!("# 框架: {}\n", fws.join(", ")));
    }
    toml.push('\n');

    // [project]
    toml.push_str(&format!("[project]\nname = \"{}\"\n", scan.project_name));
    toml.push_str(&format!("root_path = \"{}\"\n\n", scan.root_path));

    // [layers] — 四层文档模型
    toml.push_str("# 四层文档模型\n[layers]\n");
    toml.push_str("# 宪法与边界层（AI 编码约束）\n");
    toml.push_str(&format!("rule_paths = [{}]\n", rule_paths.join(", ")));
    toml.push_str("# 状态与记忆层（AI 工作记忆，需定期 GC）\n");
    toml.push_str("state_paths = [\".ai/progress.md\"]\n");
    toml.push_str("state_capacity = 100  # 行数上限，超出自动触发 GC\n");
    toml.push_str("archive_dir = \".ai/archive\"\n");
    toml.push_str("# 契约与蓝图层（设计文档、API 规范）\n");
    if scan.existing_docs.docs_dir.is_some() {
        toml.push_str("contract_paths = [\"docs/design/*.md\"]\n");
    } else {
        toml.push_str("contract_paths = []\n");
    }
    toml.push_str("# 决策快照层（架构决策记录，只读）\n");
    if scan.existing_docs.docs_dir.is_some() {
        toml.push_str("decision_paths = [\"docs/adr/*.md\"]\n");
    } else {
        toml.push_str("decision_paths = []\n");
    }

    // [scan] — 扫描配置
    toml.push_str("\n# 扫描配置\n[scan]\n");
    toml.push_str("# 扫描时排除的目录（glob 格式）\n");
    toml.push_str("exclude_dirs = [\"node_modules\", \"target\", \"dist\", \".git\", \"__pycache__\"]\n");
    toml.push_str("# 依赖树深度解析\n");
    toml.push_str("parse_dependencies = true\n");
    toml.push_str("# CI 配置解析\n");
    toml.push_str("parse_ci_config = true\n");

    // [gc]
    toml.push_str("\n# 记忆垃圾回收配置\n[gc]\n");
    toml.push_str("enabled = true\n");
    toml.push_str("interval_minutes = 30\n");
    toml.push_str("auto_commit = false\n");
    toml.push_str("commit_message_template = \"docs(gc): archive completed items from {source}\"\n");

    // [governance] — 治理闭环
    toml.push_str("\n# 治理框架偏差检测 (F6)\n[governance]\n");
    toml.push_str("# 自动检测 AGENTS.md 与项目现状的偏差\n");
    toml.push_str("drift_detection = true\n");
    toml.push_str("# 检测维度: language, framework, tool, directory, section, ci, testing\n");
    toml.push_str("drift_dimensions = [\"language\", \"framework\", \"tool\", \"directory\", \"section\", \"ci\", \"testing\"]\n");

    // [conflict_detection]
    toml.push_str("\n# 知识冲突检测 (F3)\n[conflict_detection]\n");
    toml.push_str("enabled = false  # Phase 3 启用\n");
    if scan.git_stats.is_git_repo {
        toml.push_str("watch_branches = [\"main\"]\n");
    }
    toml.push_str("exclude_paths = [\"docs/adr/*\"]  # ADR 只读，不检测冲突\n");

    // [rule_extraction]
    toml.push_str("\n# 隐式规则提取 (F2)\n[rule_extraction]\n");
    toml.push_str("enabled = false  # Phase 2 启用\n");
    toml.push_str("failure_log = \".ai/failures.jsonl\"\n");
    toml.push_str("min_frequency = 3\n");
    toml.push_str("target_files = [\"AGENTS.md\"]\n");

    // [pruner]
    toml.push_str("\n# 冗余文档清理 (F4)\n[pruner]\n");
    toml.push_str("enabled = false  # Phase 4 启用\n");
    toml.push_str("interval_days = 7\n");
    toml.push_str("scan_extensions = [\"md\", \"txt\", \"rst\"]\n");

    // [llm] — 不再硬编码 provider，留空让用户配置
    toml.push_str("\n# LLM 配置（留空则使用全局 ~/.docguardian/llm_config.json）\n[llm]\n");
    toml.push_str("# provider = \"ollama\"  # openai | claude | zhipu | deepseek | ollama | custom\n");
    toml.push_str("# model = \"llama3.1:8b\"\n");
    toml.push_str("# base_url = \"http://localhost:11434\"\n");
    toml.push_str("# api_key = \"\"  # 建议使用环境变量而非硬编码\n");
    toml.push_str("max_tokens_per_request = 16384\n");

    toml
}
